site_name: Dokumentasi KRSRI Barelang F1



nav:
  - Home: index.md
  - Setup Utama: 2-setup.md
  - Instalasi Software: 3-instalasiSoftware.md
  - Object Detection: 4-instalasiVision.md



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details



theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - content.tabs.link
  
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: fontawesome/brands/windows
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: fontawesome/brands/linux
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  font:
    code: Red Hat Mono
  
  logo: assets/pictures/F1 Logo.jpg
  favicon: assets/pictures/F1Maskot.png

  palette: 
    scheme: slate
    primary: red
    accent: light green


extra:
  annotate:
    json: [.s2]


## Login screen (comment out to disable)
#extra_javascript:
  #- assets/auth.js